#!/bin/bash
echo "Patching frameworks_native -> STE OMX Fix"
cd frameworks/native
git fetch https://gerrit.omnirom.org/android_frameworks_native refs/changes/34/6834/1 && git cherry-pick FETCH_HEAD
echo "----------------------------------------"
echo "Patching frameworks_native -> Fix buffering on STE devices"
git fetch https://gerrit.omnirom.org/android_frameworks_native refs/changes/27/6827/1 && git cherry-pick FETCH_HEAD
cd ..
echo "----------------------------------------"
echo "Patching frameworks_av -> STE Multimedia Fix"
cd av
git fetch https://gerrit.omnirom.org/android_frameworks_av refs/changes/28/6828/1 && git cherry-pick FETCH_HEAD
cd ..
echo "----------------------------------------"
echo "Patching frameworks_base -> Fix STE OMX"
cd base
git fetch https://gerrit.omnirom.org/android_frameworks_base refs/changes/29/6829/1 && git cherry-pick FETCH_HEAD
echo "SystemUI: add missing status bar image"
git fetch https://gerrit.omnirom.org/android_frameworks_base refs/changes/33/6833/1 && git cherry-pick FETCH_HEAD
cd ../..
echo "----------------------------------------"
echo "Patching system_core -> STE OMX Fix + Fix shutdown/reboot bug"
cd system/core
git fetch https://gerrit.omnirom.org/android_system_core refs/changes/30/6830/1 && git cherry-pick FETCH_HEAD
git fetch https://gerrit.omnirom.org/android_system_core refs/changes/31/6831/1 && git cherry-pick FETCH_HEAD
cd ../..
echo "low incoming call fix"
cd packages/services/Telephony
git fetch https://gerrit.omnirom.org/android_packages_services_Telephony refs/changes/32/6832/1 && git cherry-pick FETCH_HEAD
cd ../../..
echo "----------------------------------------"
echo "Patching bootable_recovery -> fix compile issue - undefined reference to 'gr_maxExW'"
cd bootable/recovery
git fetch https://gerrit.omnirom.org/android_bootable_recovery refs/changes/04/5804/1 && git checkout FETCH_HEAD
cd ../..
echo "----------------------------------------"
echo "DONE"
exit 0
