#!/bin/bash
repo sync -d || exit 1
repo forall -c 'git reset --hard' || exit 1
repo forall -c 'git clean -f -d' || exit 1
repo sync || exit 1
if [ "$1" = "--with-pull" ]; then
./device/samsung/golden/golden_pull
fi
exit 0
